categories = [
  ["Full-Service Restaurant", "North American"],
  ["Full-Service Restaurant", "Other (Restaurant)"],
  ["Entertainment", "Athletic Spectator Sports"],
  ["Retail", "Food/Drink"],
  ["Full-Service Restaurant", "European"],
  ["Fitness/Active", "Yoga Studio"],
  ["Full-Service Restaurant", "Asian"],
  ["Entertainment", "Museums"],
  ["Entertainment", "Tours"],
  ["Entertainment", "City Attractions"],
  ["Entertainment", "Art Studio/Center"],
  ["Entertainment", "Specialty Sports/Racing"],
  ["Fitness/Active", "Extreme/Adventure Sports"],
  ["Entertainment", "Beer/Wine/Spirits"],
  ["Entertainment", "Boating"],
  ["Restaurants", "French"],
  ["Food & Drink", "Specialty Food"],
  ["Arts and Entertainment", "Alcohol Event"],
  ["Arts and Entertainment", "Arts/Crafts/Hobbies"],
  ["Restaurants", "Sandwich/Deli"],
  ["Health & Fitness", "Golf"],
  ["Restaurants", "Asian/Sushi"],
  ["Food & Drink", "Ice Cream & Frozen Yogurt"],
  ["Nightlife", "Bars"],
  ["Restaurants", "Creperies"],
  ["Restaurants", "Gastropubs"],
  ["Arts and Entertainment", "Outdoor Pursuits"],
  ["Arts and Entertainment", "Arcades"],
  ["Restaurants", "Chinese"],
  ["Restaurants", "Mediterranean"],
  ["Restaurants", "Thai"],
  ["Arts and Entertainment", "Skating"],
  ["Arts and Entertainment", "Paintball"],
  ["Arts and Entertainment", "Bowling"],
  ["Arts and Entertainment", "Hot Air Balloon"],
  ["Nightlife", "Comedy Clubs"],
  ["Restaurants", "Barbeque"],
  ["Food & Drink", "Dessert/Bakery"],
  ["Restaurants", "Cafe"],
  ["Education", "Cooking Classes"],
  ["Arts and Entertainment", "Entertainment"],
  ["Restaurants", "Burgers"],
  ["Arts and Entertainment", "Amusement Parks"],
  ["Arts and Entertainment", "Zoos"],
  ["Arts and Entertainment", "Boating"],
  ["Arts and Entertainment", "Music Concert"],
  ["Arts and Entertainment", "Sporting Events"],
  ["Entertainment", "Performing Art Center/Theater"],
  ["Full-Service Restaurant", "Central and South American"],
  ["Full-Service Restaurant", "African/Middle Eastern"],
  ["Arts and Entertainment", "Dance"],
  ["Restaurants", "Italian Restaurant"],
  ["Arts and Entertainment", "Dinner Theater"],
  ["Health & Fitness", "Yoga"],
  ["Arts and Entertainment", "Horse/Carriage Ride"],
  ["Restaurants", "American/Traditional"],
  ["Food & Drink", "Wine Shops"],
  ["Entertainment", "Culinary Classes"],
  ["Entertainment", "Nightlife"],
  ["Arts and Entertainment", "Miniature Golf"],
  ["Nightlife", "Pubs/Sports Bars"],
  ["Food & Drink", "Breweries"],
  ["Arts and Entertainment", "Water Parks"],
  ["Arts and Entertainment", "Bike Tours"],
  ["Arts and Entertainment", "Theater & Plays"],
  ["Restaurants", "Moroccan"],
  ["Arts and Entertainment", "Festivals"],
  ["Restaurants", "Korean"],
  ["Restaurants", "Fine Dining"],
  ["Arts and Entertainment", "Art Galleries"],
  ["Restaurants", "Pizza"],
  ["Arts and Entertainment", "Opera"],
  ["Nightlife", "Night Clubs"],
  ["Restaurants", "Brazilian"],
  ["Restaurants", "Tea Rooms"],
  ["Arts and Entertainment", "Go Karts"],
  ["Restaurants", "Japanese"],
  ["Arts and Entertainment", "Museum"]
]

EVENT_CATEGORIES = []

categories.each do |cat|
  EVENT_CATEGORIES << Event::Category.new(cat[0], cat[1])
end