source 'https://rubygems.org'

gem 'rails', '3.2.6'
gem 'sqlite3'
gem 'rspec-rails'
gem 'faraday'
gem 'mongoid'
gem 'bson_ext'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'nokogiri'
gem 'money'
gem 'kaminari'
gem 'whenever', :require => false