# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Image.create([
  { :user_id => 14, :image_url => "http://distilleryimage8.instagram.com/ce38c5c8c3ff11e1b9f1123138140926_6.jpg", :width => nil, :height => nil, :created_at => "2012-07-03 07:09:32", :updated_at => "2012-07-03 07:09:32" },
  { :user_id => 14, :image_url => "http://distilleryimage10.instagram.com/bfd8c600c1dd11e188131231381b5c25_6.jpg", :width => nil, :height => nil, :created_at => "2012-07-03 07:09:32", :updated_at => "2012-07-03 07:09:32" },
  { :user_id => 14, :image_url => "http://distilleryimage3.s3.amazonaws.com/ea207d8074e511e181bd12313817987b_7.jpg", :width => nil, :height => nil, :created_at => "2012-07-03 07:09:32", :updated_at => "2012-07-03 07:09:32" },
  { :user_id => 13, :image_url => "http://distilleryimage4.s3.amazonaws.com/71cdb9bea45711e1a9f71231382044a1_6.jpg", :width => "306", :height => "306", :created_at => "2012-07-03 07:10:28", :updated_at => "2012-07-03 07:10:28" },
  { :user_id => 13, :image_url => "http://distilleryimage7.s3.amazonaws.com/6000791ca38311e192e91231381b3d7a_6.jpg", :width => "306", :height => "306", :created_at => "2012-07-03 07:10:32", :updated_at => "2012-07-03 07:10:32" },
  { :user_id => 13, :image_url => "http://distilleryimage8.s3.amazonaws.com/5a3217b4332811e19e4a12313813ffc0_6.jpg", :width => "306", :height => "306", :created_at => "2012-07-03 07:10:34", :updated_at => "2012-07-03 07:10:34" }
])

User.create([
  { :email => "jessica@gmail.com", :encrypted_password => "$2a$10$CmZXbr/0DQy2jwr8j6RUpuW6n5E04KonYcYD56L/L1Jwi5QG7BlYy", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 0, :current_sign_in_at => nil, :last_sign_in_at => nil, :current_sign_in_ip => nil, :last_sign_in_ip => nil, :created_at => "2012-07-03 07:09:31", :updated_at => "2012-07-03 07:09:31", :uid => nil, :provider => nil, :oauth_access_token => nil, :authentication_token => "4DZ7jz5ZfHP377j4sJR9", :display_name => "jessica", :birthday => "1986-07-10", :slug => "jessica" },
  { :email => "edweng@gmail.com", :encrypted_password => "$2a$10$ynxGoMwH6m4ytmEN97mB4.Z8TE9IiGkowyqGFrooDBEG6nxDGdMQG", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 2, :current_sign_in_at => "2012-07-03 07:10:13", :last_sign_in_at => "2012-07-03 07:09:58", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :created_at => "2012-07-03 07:09:30", :updated_at => "2012-07-03 07:10:13", :uid => nil, :provider => nil, :oauth_access_token => nil, :authentication_token => "RG9xmVerqHkVsy4p9d7S", :display_name => "edweng", :birthday => "1988-06-21", :slug => "edweng" }
])

UserDetail.create([
  { :user_id => 14, :image_url => "http://distilleryimage9.s3.amazonaws.com/bd5d306ec4d011e1bf341231380f8a12_6.jpg", :gender => "female", :gender_preference => "men", :age_range_lower => nil, :age_range_upper => nil, :employment => "Computer Programmer", :education => "2", :faith => nil, :faith_level => nil, :political_affiliation => nil, :political_affiliation_level => nil, :race => nil, :children_preference => nil, :exercise_level => nil, :drinking_level => nil, :smoking_level => nil, :created_at => "2012-07-03 07:09:32", :updated_at => "2012-07-03 07:09:32", :zipcode => "20036", :latitude => 38.9080786, :longitude => -77.0406147, :city => "Washington", :state => "District of Columbia", :country => "United States", :height => "5\"9" },
  { :user_id => 13, :image_url => "http://distilleryimage7.s3.amazonaws.com/2943b926be5d11e1b2fe1231380205bf_6.jpg", :gender => "male", :gender_preference => "women", :age_range_lower => nil, :age_range_upper => nil, :employment => "Bonobos Model", :education => "4", :faith => "3", :faith_level => nil, :political_affiliation => "3", :political_affiliation_level => nil, :race => "1", :children_preference => "2", :exercise_level => nil, :drinking_level => nil, :smoking_level => nil, :created_at => "2012-07-03 07:09:31", :updated_at => "2012-07-03 07:19:34", :zipcode => "20036", :latitude => 38.9080786, :longitude => -77.0406147, :city => "Washington", :state => "District of Columbia", :country => "United States", :height => "5\"8" }
])


