source 'https://rubygems.org'

gem 'rails', '3.2.3'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'pg'
gem 'devise'
gem 'omniauth-facebook'
gem 'koala'
gem 'twitter-bootstrap-rails', :git => 'git://github.com/seyhunak/twitter-bootstrap-rails.git'
gem 'feynman_client', :require => 'feynman', :git => 'git@github.com:wengzilla/feynman_gem.git'
gem 'spine-rails'
gem 'eco'
gem 'jbuilder'
gem 'random_data'
gem 'carrierwave'
gem 'hashie'
gem 'mongoid'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platform => :ruby

  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  gem 'sqlite3'
  gem 'rack-test'
  gem 'guard'
  gem 'capybara'
  gem 'simplecov'
  gem 'launchy'
  gem 'debugger'
  gem 'awesome_print'
  gem 'factory_girl'
  gem 'rack-test'
  gem 'rspec-rails'
  gem 'guard'
  gem 'guard-rspec'
  gem 'ruby_gntp'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
