source 'https://rubygems.org'

gem 'rails', '3.2.6'
gem 'sqlite3'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'capybara'
  gem 'launchy'
  gem 'fabrication'
  gem 'database_cleaner'
end

gem 'jquery-rails'
gem 'mongoid'
gem 'bson_ext'
gem 'devise'
gem "twitter-bootstrap-rails"
gem 'classifier'
