development:
  host: localhost
  database: newton_development

test:
  host: localhost
  database: newton_test

# set these environment variables on your prod server
production:
  host: localhost
  database: newton
